name: build
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/*.cpp'
      - 'include/*.h'
      - '*.py'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Update System
        run: sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.51.3

      - name: Create conan profile
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      # If we need to build sdl_mixer from source make sure all features are available, see:
      # https://discourse.libsdl.org/t/couldnt-open-audio-device-no-available-audio-device/18499
      # https://github.com/libsdl-org/SDL/blob/9325b22ef03302d80b6ab9a4eade362f22f9657e/docs/README-linux.md#l1
      - name: Install sdl_mixer features
        run: |
          sudo apt-get install build-essential mercurial make cmake autoconf automake \
          libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev \
          libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev \
          libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev libwayland-dev \
          libxkbcommon-dev

      - name: Create package
        run: |
          sudo conan create . --build=missing -c tools.system.package_manager:mode=install

      - uses: grisumbras/locate-conan-package@latest
        id: locate_package

      - name: Upload package
        uses: actions/upload-artifact@v1
        with:
          name: artifacts-linux
          path: ${{ steps.locate_package.outputs.path }}

