name: build
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - 'src/*.cpp'
      - 'include/*.h'
      - '*.py'
  push:
    paths:
      - 'src/*.cpp'
      - 'include/*.h'
      - '*.py'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Update System
        run: sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Get Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 1.51.3

      - name: Create conan profile
        run: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default

      # Required for conan package creation
      - name: Install system packages
        run: |
          sudo apt-get install libx11-xcb-dev libfontenc-dev libxaw7-dev libxcomposite-dev \
          libxdamage-dev libxmu-dev libxmuu-dev libxpm-dev libxres-dev libxtst-dev libxv-dev \
          libxvmc-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev \
          libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev \
          libxcb-xfixes0-dev libxcb-xinerama0-dev libxcb-dri3-dev libxcb-util-dev libxcb-util0-dev

      # If we need to build sdl_mixer from source make sure all features are available, see:
      # https://discourse.libsdl.org/t/couldnt-open-audio-device-no-available-audio-device/18499
      # https://github.com/libsdl-org/SDL/blob/9325b22ef03302d80b6ab9a4eade362f22f9657e/docs/README-linux.md#l1
      - name: Install sdl_mixer features
        run: |
          sudo apt-get install build-essential mercurial make cmake autoconf automake \
          libtool libasound2-dev libpulse-dev libaudio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxxf86vm-dev libxss-dev \
          libgl1-mesa-dev libdbus-1-dev libudev-dev libgles2-mesa-dev libegl1-mesa-dev \
          libibus-1.0-dev fcitx-libs-dev libsamplerate0-dev libsndio-dev libwayland-dev \
          libxkbcommon-dev

      - name: Create package
        run: |
          conan create . --build=missing --json info.json

      - uses: ianmurfinxyz/parse-package-json@v1.0
        id: info
        with:
          json-path: 'info.json'

      - name: Print package info
        run: |
          echo ${{ steps.info.outputs.recipe_id }}
          echo ${{ steps.info.outputs.package_id }}
          echo ${{ steps.info.outputs.root_path }}
          echo ${{ steps.info.outputs.version }}

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.info.outputs.root_path }} 

